module Pzl.Sites.Core.Resources {
    export var Provisioning_progressbar_id = "js-sites-core-progress";
    export var Provisioning_progressbar_text_id  = "js-sites-core-progress-text";
    export var Provisioning_progressbar_markup = `<div class="progress-bar" role="progressbar" aria-valuenow="{0}" aria-valuemin="0" aria-valuemax="100" style="width:{0}%">{0}%</div>`;
    export var Provisioning_started = "Starting at URL {0}";
    export var Provisioning_ended = "Done in {0} seconds";
    export var Provisioning_timeout = "Timeout for {0} seconds";
    export var WaitMessage_header = "Applying template";
    export var WaitMessage_content = "This might take a moment.";
    export var Code_execution_started = "Code execution scope started";
    export var Code_execution_ended = "Code execution scope ended";
    export var Lists_list_already_exists = "A list with the specified title {0} already exists in this Web site at Url {1}";
    export var Lists_creating_list = "Creating list with title {0} at Url {1}";
    export var Lists_creating_folder = "Creating folder {0}";
    export var Lists_setting_default_value_for_folder = "Setting default value '{0}' = '{1}' for folder '{2}'";
    export var Lists_setting_default_metadata = "Setting default metadata for folder {0}";
    export var Lists_enabled_content_types = "Enabled content types for list {0}";
    export var Lists_removing_content_type = "Removing content type {0} from list {1}";
    export var Lists_adding_content_type = "Adding content type {0} to list {1}";
    export var Lists_breaking_role_inheritance = "Breaking Role Inheritance for list {0}";
    export var Lists_role_assignments_applied = "Role assignements applied for list {0}";
    export var Lists_updating_list_view = "Updating existing view {0} for list {1}";
    export var Lists_adding_list_view = "Adding view {0} for list {1}";
    export var Lists_removing_existing_list_view = "Removing existing view {0} for list {1}";
    export var Lists_adding_eventreceiver = "Adding eventreceiver {0} to list {1}";
    export var Lists_adding_field_ref = "Adding field {0} to list {1}";
    export var Lists_adding_field = "Adding {0} field '{1}' to list '{2}'";
    export var Lists_adding_lookup_field = "Adding {0} lookup field '{1}' to list '{2}'";
    export var Lists_adding_field_schema_xml = "Adding field to list '{0}', using Schema XML";
    export var Lists_invalid_lookup_field = "The lookup field '{0}' for list '{1}' is invalid";
    export var Lists_inserting_data_row = "Adding data row {0} of {1} to list '{2}'";
    export var Lists_adding_ribbon_action = "Adding ribbon action '{0}' to list '{1}'";
    export var Lists_adding_ribbon_action_dependency = "Adding custom action for dependency for ribbon action '{0}' for list '{1}'"
    export var WebSettings_setting_welcomePage = "Setting welcome page to {0}";
    export var WebSettings_setting_alternateCssUrl = "Setting alternate css url to {0}";
    export var WebSettings_setting_masterUrl = "Setting master url to {0}";
    export var WebSettings_setting_customMasterUrl = "Setting custom master url to {0}";
    export var WebSettings_setting_saveSiteAsTemplateEnabled = "Setting save site as template enabled to {0}";
    export var WebSettings_setting_quickLaunchEnabled = "Setting quicklaunch enabled to {0}";
    export var WebSettings_setting_recycleBinEnabled= "Setting recyclebin enabled to {0}";
    export var WebSettings_setting_treeViewEnabled = "Setting treeview enabled to {0}";
    export var PropertyBagEntries_setting_property = "Setting property '{0}' = '{1}' on web";
    export var PropertyBagEntries_setting_indexed_property = "Setting property '{0}' as indexed";
    export var Pages_creating_page = "Creating wiki page with Url {0}";
    export var Pages_creating_page_failed = "Failed to create wiki page with Url {0}";
    export var Navigation_setting_shared = "Setting useShared to {0}";
    export var Navigation_configuring_of_quicklaunch_done = "Configuring of quicklaunch done";
    export var Navigation_configuring_of_quicklaunch_failed = "Configuring of quicklaunch failed";
    export var Navigation_configuring_quicklaunch_navigation = "Configuring quicklaunch navigation";
    export var Navigation_removing_existing_nodes = "Removing existing navigation nodes";
    export var Navigation_adding_node = "Adding navigation node with Url {0} and Title {1}";
    export var Navigation_adding_children_node = "Adding navigation node with Url {0} and Title {1}, under parent {2}";
    export var CustomAction_already_exists = "A custom action with Title '{0}' already exists";
    export var CustomAction_creating = "Creating custom action with Title '{0}'";
    export var Files_retrieving_xml_for_webpart = "Retrieving XML for webpart '{0}' from file";
    export var Files_removing_existing_webparts = "Removing existing webparts for file with URL '{0}'";
    export var Files_adding_webpart = "Adding web part '{0}' to zone '{1}' for file with URL '{2}'";
    export var Files_setting_properties = "Setting properties for file with URL {0}";
    export var Files_setting_property = "Setting property '{0}' = '{1}' for file with URL '{2}'";
    export var Files_retrieved_file_contents = "Retrieved content for file with Url '{0}' from source file";
    export var Files_creating_file = "Creating file with Url '{0}'"
    export var Files_skipping_form_file = "File with Url {0} is a form file. Skipping creation.";
    export var Files_modifying_list_views = "Modifying list views for list '{0}'";
    export var Files_modifying_list_view = "Modifying list view with Url '{0}' for list '{1}'";
    export var Features_activating_feature = "Activating feature with ID '{0}'";
    export var Features_deactivating_feature = "Deactivating feature with ID '{0}'";
    export var ComposedLook_applying_theme = "Applying theme. Color file '{0}' and font file '{1}'."
}
