module Pzl.Sites.Core.Resources {
    export var Provisioning_started = "Starting at URL {0}";
    export var Provisioning_ended = "Done in {0} seconds";
    export var WaitMessage_header = "Applying template";
    export var WaitMessage_content = "This might take a moment.";
    export var Code_execution_started = "Code execution scope started";
    export var Code_execution_ended = "Code execution scope ended";
    export var Lists_list_already_exists = "A list with the specified title {0} already exists in this Web site at Url {1}";
    export var Lists_creating_list = "Creating list with title {0} at Url {1}";
    export var Lists_creating_folder = "Creating folder {0}";
    export var Lists_setting_default_metadata = "Setting default metadata for folder {0}";
    export var Lists_enabled_content_types = "Enabled content types for list {0}";
    export var Lists_removing_content_type = "Removing content type {0} from list {1}";
    export var Lists_adding_content_type = "Adding content type {0} to list {1}";
    export var Lists_breaking_role_inheritance = "Breaking Role Inheritance for list {0}";
    export var Lists_role_assignments_applied = "Role assignements applied for list {0}";
    export var Lists_updating_list_view = "Updating existing view {0} for list {1}";
    export var Lists_adding_list_view = "Adding view {0} for list {1}";
    export var Lists_adding_eventreceiver = "Adding eventreceiver {0} to list {1}";
    export var Lists_adding_field_ref = "Adding field {0} to list {1}";
    export var WebSettings_setting_welcomePage = "Setting welcome page to {0}";    
    export var WebSettings_setting_alternateCssUrl = "Setting alternate css url to {0}";    
    export var WebSettings_setting_masterUrl = "Setting master url to {0}";    
    export var WebSettings_setting_customMasterUrl = "Setting custom master url to {0}";    
    export var WebSettings_setting_saveSiteAsTemplateEnabled = "Setting save site as template enabled to {0}";    
    export var WebSettings_setting_quickLaunchEnabled = "Setting quicklaunch enabled to {0}";    
    export var WebSettings_setting_recycleBinEnabled= "Setting recyclebin enabled to {0}";    
    export var WebSettings_setting_treeViewEnabled = "Setting treeview enabled to {0}";
    export var PropertyBagEntries_setting_propety = "Setting property '{0}' = '{1}' on web";
}